# Generated by Django 3.0.2 on 2020-01-16 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200114_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
